name: Code Formatting

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f # v3.2.0
        with:
          python-version: 3.9
          auto-update-conda: true
          environment-file: environment.dev.yaml
          activate-environment: test

      - name: Check code formatting with Black
        shell: bash -el {0}
        run: |
          black --check --diff $(git ls-files '*.py')
