name: Code Formatting

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
        with:
          python-version: 3.9
          auto-update-conda: true
          environment-file: environment.dev.yaml
          activate-environment: test

      - name: Check code formatting with Black
        shell: bash -el {0}
        run: |
          black --check --diff $(git ls-files '*.py')
